# Generated by Django 5.0.2 on 2024-03-12 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_publication_article'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='Publication',
            new_name='publications',
        ),
    ]
